FROM php:zts-bullseye

RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN pecl install mongodb
RUN docker-php-ext-enable mongodb

WORKDIR /app

COPY ./backend .

RUN composer install

CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

EXPOSE 8000